### ISSUE TITLE
Still Regular Trees in World(1.12.2)

### ISSUE THREAD

**Issue by KenyMylankca** [DynamicTreesTeam/DynamicTrees-BOP#54] opened 2020-09-24 12:27 UTC
as you can see in flower forest biome(don't mind the "plains" under the map, i did move 2 steps away from that), there are regular oak trees with flowering oak leaves.
![2020-09-24_15 24 59](https://user-images.githubusercontent.com/41585837/94144799-45e01500-fe7a-11ea-8e83-797e831252f2.png)
used:
DynamicTrees-1.12.2-0.9.15
DynamicTreesBOP-1.12.2-1.4.2
BiomesOPlenty-1.12.2-7.0.1.2444-universal
also you can find the modpack i used in, in my profile, called kenijey's modpack

**Comment by supermassimo** [comment] 2023-05-14 15:57
Duplicate of https://github.com/DynamicTreesTeam/DynamicTrees-BOP/issues/24

**Closed by supermassimo** 2023-05-14 15:57 UTC
Labels: bug, 1.12.2
