### ISSUE TITLE
Sacred Springs Biome 

### ISSUE THREAD

**Issue by mossjones** [DynamicTreesTeam/DynamicTrees-BOP#58] opened 2020-12-07 19:12 UTC
Trees in the Sacred Springs Biome aren't dynamic.
Temp, work around. (Just disable the biome in BoP settings)

The Picture below is an example of a Dynamic Jungle Biome next to a non-dynamic Sacred Springs Biome.
![Screenshot_8](https://user-images.githubusercontent.com/49288710/101394169-214ee300-3896-11eb-9eab-1047f1674764.png)

**Comment by KenyMylankca** [comment] 2021-05-04 10:24
yeah, please fix this.

**Comment by supermassimo** [comment] 2021-05-04 15:21
I will take a look!

**Comment by KenyMylankca** [comment] 2021-05-04 15:28
thanks a lot! btw we're on 1.12.2

**Comment by KenyMylankca** [comment] 2023-04-24 09:34
still nothing? :/

**Comment by supermassimo** [comment] 2023-05-14 15:54
Duplicate of https://github.com/DynamicTreesTeam/DynamicTrees-BOP/issues/54

**Closed by supermassimo** 2023-05-14 15:54 UTC
Labels: bug, 1.12.2
